### ISSUE TITLE
Scopes

### ISSUE THREAD

**Issue by PeterTippett** [quickaco/xerosdk#1]
The Scopes need to be space-delimited, not comma

The reason is the Migration code for Xero will only work with space-delimited data while the OAutho2 code works with comma as well.

Xero documentation also states space delimited.

**Comment by ramonmacias** [comment]
Hi @PeterTippett thanks for the issue!

I think you refer to the code inside the example folder (main.go), on the init function we take this Scopes from a .env file which is comma-delimited, so means you can use another different format of fill this envvars. If you go to the auth package you can see that we use golang.org/x/oauth2 package for handle all the stuff related with OAuth2, also if go deep on this package you will see we are using this method AuthCodeURL which basically build the URL we need to send to Xero in order to start the OAuth2 process, basically is doing this v.Set("scope", strings.Join(c.Scopes, " ")) so is on this part where we build from []string to this space-delimited scopes.

I hope this will help you!

Thanks!

**Comment by PeterTippett** [comment]
Your read.me states comma to be used, but inside the code, you then convert to space.

This then creates confusion as I see it as I just pulled this code for building the body for the Migrate code from the .env data I had which caused the failure and the error messages aren't that great so took a while to solve.

**Comment by ramonmacias** [comment]
sorry @PeterTippett you are right, probably I need to write more documentation and just separte this specific example use case from the general way to use this package, I will work on improve this documentation.

Thanks again for the feedback!

**Comment by PeterTippett** [comment]
That's OK.

Really like how simple the code you have. I've had to do some changes as using Google App Engine Go1.11, but once I move to Go1.14, can then do an update on this with a database backing it.

Also, Xero aren't supporting the upgrade of the old 1.0a GoLang library as they have no GoLang programmers to support it.

Also used the OpenSDK API spec they have to create my model's so they are always current, just dealing with JSON issues on field.field.field data missing like in Contacts which the old models had no problems with.

**Comment by ramonmacias** [comment]
Yes, we had the same problem, we started the integration with Xero using the old 1.0a but then we realised that is no longer supported and also we couldn't create new xero apps with the OAuth1.

Also as you said there is no official support for OAuth2 in GoLang so this is why we decided to implement the new SDK with OAuth2, so basically we reuse the olt types from the old SDK and apply the new OAuth2 client on it, so we try to keep the same functionality but just with a new way to handle the connection.

Currently we are using the contact and invoice API in our project and works properly, but we didn't implement yet the part with payments and other stuff from the AccountingAPI, is there but we didn't use so can be some bugs on this part.

**Comment by PeterTippett** [comment]
I made a deliberate change of the models to being driven by the Swagger Export from the Xero OpenAPI so if they do any updates so I can handle them automatically.  Just a bit frustrated in how the GoLang JSON code handles the nil values of subfields.

The reason for doing this is I will also be linking to other products, so want to be as clean as possible.

Quickbooks are constantly adding to their API new fields in their subversions they release.

**Comment by smingam** [comment]
First of all, a big thank you for your work!
Like you, I have an application with the old SDK with oauth 1 that need oauth2, so I hope I can use and contribute to your project !

Just wanted to leave it somewhere because I spent, to my discredit, too much time wondering what's going on:
If you leave in the .env the comment `// Comma separated fields`, you will get an `Error code: 500 Error: invalid_scope : Invalid scope` error and be quite puzzled. After triple checking and trying with success the [golang-oauth2-example](https://github.com/XeroAPI/golang-oauth2-example/blob/main/server/server.go), you will finally print the scopes array and realize that the scopes string is split on commas, not spaces and therefor `"offline_access // Comma separated fields"` is quite rightly an invalid scope.

Hope it helps someone!
Cheers

PS: in .env files, comment is "#" character ?
